version: '3.8'

services:
  app:
    build: .
    container_name: fraudit-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/fraudit
      - SPRING_DATASOURCE_USERNAME=fraudit_user
      - SPRING_DATASOURCE_PASSWORD=fraudit_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_PROFILES_ACTIVE=prod
      - PORT=8080
    volumes:
      - ./uploads:/opt/render/project/uploads
    restart: always

  db:
    image: postgres:15.2-alpine
    container_name: fraudit-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=fraudit_user
      - POSTGRES_PASSWORD=fraudit_password
      - POSTGRES_DB=fraudit
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: