services:
  - type: web
    name: fraudit
    env: docker
    region: oregon  # Or your preferred region
    plan: free
    branch: master  # Or your main branch name
    healthCheckPath: /health
    healthCheckTimeout: 120  # Increase timeout for health checks
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_FLYWAY_BASELINE_ON_MIGRATE
        value: true
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: validate
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: PORT
        value: 8080
      - key: SERVER_PORT
        value: 8080
    disk:
      name: fraudit-data
      mountPath: /opt/render/project/uploads
      sizeGB: 1

databases:
  - name: fraudit-db
    plan: free
    region: oregon  # Should match your web service region