services:
  - type: web
    name: fraudit
    env: docker
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /health
    healthCheckTimeout: 180
    autoDeploy: false
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: validate
      - key: PORT
        value: "8080"
      - key: SERVER_PORT
        value: "8080"
      - fromDatabase:
          name: fraudit-db
          property: connectionString
        key: SPRING_DATASOURCE_URL
      - fromDatabase:
          name: fraudit-db
          property: user
        key: SPRING_DATASOURCE_USERNAME
      - fromDatabase:
          name: fraudit-db
          property: password
        key: SPRING_DATASOURCE_PASSWORD
    disk:
      name: fraudit-data
      mountPath: /opt/render/project/uploads
      sizeGB: 1

databases:
  - name: fraudit-db
    plan: free
    region: oregon