services:
  - type: web
    name: fraudit
    env: docker
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /
    healthCheckTimeout: 180
    autoDeploy: false
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_FLYWAY_BASELINE_ON_MIGRATE
        value: "true"
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: validate
      - key: PORT
        value: "8080"
      - key: SERVER_PORT
        value: "8080"
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
    disk:
      name: fraudit-data
      mountPath: /opt/render/project/uploads
      sizeGB: 1

databases:
  - name: fraudit-db
    plan: free
    region: oregon